ALTS_DICT = {
    'Special Week': {'alts': {1: 'Base', 2: 'Summer'}, 'uma_number': '1001'},
    'Silence Suzuka': {'alts': {1: 'Base', 2: 'Summer'}, 'uma_number': '1002'},
    'Tokai Teio': {'alts': {1: 'Base', 2: 'Anime'}, 'uma_number': '1003'},
    'Maruzensky': {'alts': {1: 'Base', 2: 'Summer'}, 'uma_number': '1004'},
    'Fuji Kiseki': {'alts': {1: 'Base', 2: 'Ballroom'}, 'uma_number': '1005'},
    'Oguri Cap': {'alts': {1: 'Base', 2: 'Christmas'}, 'uma_number': '1006'},
    'Gold Ship': {'alts': {1: 'Base', 2: 'Summer'}, 'uma_number': '1007'},
    'Vodka': {'alts': {1: 'Base', 2: 'Christmas'}, 'uma_number': '1008'},
    'Daiwa Scarlet': {'alts': {1: 'Base', 2: 'Christmas'}, 'uma_number': '1009'},
    'Taiki Shuttle': {'alts': {1: 'Base', 2: 'Camping'}, 'uma_number': '1010'},
    'Grass Wonder': {'alts': {1: 'Base', 2: 'Fantasy'}, 'uma_number': '1011'},
    'Hishi Amazon': {'alts': {1: 'Base', 2: 'Wedding'}, 'uma_number': '1012'},
    'Mejiro McQueen': {'alts': {1: 'Base', 2: 'Anime'}, 'uma_number': '1013'},
    'El Condor Pasa': {'alts': {1: 'Base', 2: 'Fantasy'}, 'uma_number': '1014'},
    'T.M. Opera O': {'alts': {1: 'Base', 2: 'New Year'}, 'uma_number': '1015'},
    'Narita Brian': {'alts': {1: 'Base', 2: 'Blaze'}, 'uma_number': '1016'},
    'Symboli Rudolf': {'alts': {1: 'Base', 2: 'Festival'}, 'uma_number': '1017'},
    'Air Groove': {'alts': {1: 'Base', 2: 'Wedding'}, 'uma_number': '1018'},
    'Agnes Digital': {'alts': {1: 'Base', 2: 'Halloween'}, 'uma_number': '1019'},
    'Seiun Sky': {'alts': {1: 'Base', 2: 'Ballroom'}, 'uma_number': '1020'},
    'Tamamo Cross': {'alts': {1: 'Base', 2: 'Festival'}, 'uma_number': '1021'},
    'Fine Motion': {'alts': {1: 'Base', 2: 'Wedding'}, 'uma_number': '1022'},
    'Biwa Hayahide': {'alts': {1: 'Base', 2: 'Christmas'}, 'uma_number': '1023'},
    'Mayano Top Gun': {'alts': {1: 'Base', 2: 'Wedding'}, 'uma_number': '1024'},
    'Manhattan Cafe': {'alts': {1: 'Base', 2: 'Valentine'}, 'uma_number': '1025'},
    'Mihono Bourbon': {'alts': {1: 'Base', 2: 'Valentine'}, 'uma_number': '1026'},
    'Mejiro Ryan': {'alts': {1: 'Base', 2: 'Valentine'}, 'uma_number': '1027'},
    'Hishi Akebono': {'alts': {1: 'Base', 2: 'Halloween'}, 'uma_number': '1028'},
    'Yukino Bijin': {'alts': {1: 'Base', 2: 'Valentine'}, 'uma_number': '1029'},
    'Rice Shower': {'alts': {1: 'Base', 2: 'Halloween'}, 'uma_number': '1030'},
    'Ines Fujin': {'alts': {1: 'Base', 2: 'Valentine'}, 'uma_number': '1031'},
    'Agnes Tachyon': {'alts': {1: 'Base', 2: 'Summer'}, 'uma_number': '1032'},
    'Admire Vega': {'alts': {1: 'Base', 2: 'Christmas'}, 'uma_number': '1033'},
    'Inari One': {'alts': {1: 'Base', 2: 'Festival'}, 'uma_number': '1034'},
    'Winning Ticket': {'alts': {1: 'Base', 2: 'Steampunk'}, 'uma_number': '1035'},
    'Air Shakur': {'alts': {1: 'Base', 2: 'Wedding'}, 'uma_number': '1036'},
    'Eishin Flash': {'alts': {1: 'Base', 2: 'Valentine'}, 'uma_number': '1037'},
    'Curren Chan': {'alts': {1: 'Base', 2: 'Wedding'}, 'uma_number': '1038'},
    'Kawakami Princess': {'alts': {1: 'Base', 2: 'Festival'}, 'uma_number': '1039'},
    'Gold City': {'alts': {1: 'Base', 2: 'Festival'}, 'uma_number': '1040'},
    'Sakura Bakushin O': {'alts': {1: 'Base', 2: 'Sports Fes'}, 'uma_number': '1041'},
    'Seeking the Pearl': {'alts': {1: 'Base', 2: 'Halloween'}, 'uma_number': '1042'},
    'Shinko Windy': {'alts': {1: 'Base'}, 'uma_number': '1043'},
    'Sweep Tosho': {'alts': {1: 'Base', 2: 'Wedding'}, 'uma_number': '1044'},
    'Super Creek': {'alts': {1: 'Base', 2: 'Halloween'}, 'uma_number': '1045'},
    'Smart Falcon': {'alts': {1: 'Base', 2: 'Grand Live'}, 'uma_number': '1046'},
    'Zenno Rob Roy': {'alts': {1: 'Base', 2: 'Autumn'}, 'uma_number': '1047'},
    'Tosen Jordan': {'alts': {1: 'Base', 2: 'Summer Trip'}, 'uma_number': '1048'},
    'Nakayama Festa': {'alts': {1: 'Base', 2: 'Christmas'}, 'uma_number': '1049'},
    'Narita Taishin': {'alts': {1: 'Base', 2: 'Steampunk'}, 'uma_number': '1050'},
    'Nishino Flower': {'alts': {1: 'Base', 2: 'Wedding'}, 'uma_number': '1051'},
    'Haru Urara': {'alts': {1: 'Base', 2: 'New Year'}, 'uma_number': '1052'},
    'Bamboo Memory': {'alts': {1: 'Base', 2: 'Summer Trip'}, 'uma_number': '1053'},
    'Biko Pegasus': {'alts': {1: 'Base'}, 'uma_number': '1054'},
    'Marvelous Sunday': {'alts': {1: 'Base', 2: 'Halloween'}, 'uma_number': '1055'},
    'Matikanefukukitaru': {'alts': {1: 'Base', 2: 'Full Armor'}, 'uma_number': '1056'},
    'Mr. C.B.': {'alts': {1: 'Base', 2: 'New Year'}, 'uma_number': '1057'},
    'Meisho Doto': {'alts': {1: 'Base', 2: 'Halloween'}, 'uma_number': '1058'},
    'Mejiro Dober': {'alts': {1: 'Base', 2: 'Camping'}, 'uma_number': '1059'},
    'Nice Nature': {'alts': {1: 'Base', 2: 'Cheerleader'}, 'uma_number': '1060'},
    'King Halo': {'alts': {1: 'Base', 2: 'Cheerleader'}, 'uma_number': '1061'},
    'Matikanetannhauser': {'alts': {1: 'Base', 2: 'Sports Fes'}, 'uma_number': '1062'},
    'Ikuno Dictus': {'alts': {1: 'Base', 2: 'New Year'}, 'uma_number': '1063'},
    'Mejiro Palmer': {'alts': {1: 'Base', 2: 'Christmas'}, 'uma_number': '1064'},
    'Daitaku Helious': {'alts': {1: 'Base', 2: 'Ballroom'}, 'uma_number': '1065'},
    'Twin Turbo': {'alts': {1: 'Base'}, 'uma_number': '1066'},
    'Satono Diamond': {'alts': {1: 'Base', 2: 'New Year'}, 'uma_number': '1067'},
    'Kitasan Black': {'alts': {1: 'Base', 2: 'New Year'}, 'uma_number': '1068'},
    'Sakura Chiyono O': {'alts': {1: 'Base', 2: 'Ballroom'}, 'uma_number': '1069'},
    'Sirius Symboli': {'alts': {1: 'Base', 2: 'Twinkle Legends'}, 'uma_number': '1070'},
    'Mejiro Ardan': {'alts': {1: 'Base', 2: 'Ballroom'}, 'uma_number': '1071'},
    'Yaeno Muteki': {'alts': {1: 'Base', 2: 'Warfare'}, 'uma_number': '1072'},
    'Tsurumaru Tsuyoshi': {'alts': {1: 'Base'}, 'uma_number': '1073'},
    'Mejiro Bright': {'alts': {1: 'Base', 2: 'Christmas'}, 'uma_number': '1074'},
    #'Special Week': {'alts': {1: 'Base', 2: 'Summer'}, 'uma_number': '1075'}, missing in gametora idk
    'Sakura Laurel': {'alts': {1: 'Base', 2: 'New Year'}, 'uma_number': '1076'},
    'Narita Top Road': {'alts': {1: 'Base', 2: 'Christmas'}, 'uma_number': '1077'},
    'Yamanin Zephyr': {'alts': {1: 'Base', 2: 'Valentine'}, 'uma_number': '1078'},
    'Furioso': {'alts': {1: 'Base'}, 'uma_number': '1079'},
    'Transcend': {'alts': {1: 'Base', 2: 'Onsen'}, 'uma_number': '1080'},
    'Espoir City': {'alts': {1: 'Base'}, 'uma_number': '1081'},
    'North Flight': {'alts': {1: 'Base'}, 'uma_number': '1082'},
    'Symboli Kris S': {'alts': {1: 'Base', 2: 'Halloween'}, 'uma_number': '1083'},
    'Tanino Gimlet': {'alts': {1: 'Base', 2: 'Ballroom'}, 'uma_number': '1084'},
    'Daiichi Ruby': {'alts': {1: 'Base', 2: 'Ballroom'}, 'uma_number': '1085'},
    'Mejiro Ramonu': {'alts': {1: 'Base', 2: 'Wedding'}, 'uma_number': '1086'},
    'Aston Machan': {'alts': {1: 'Base', 2: 'Valentine'}, 'uma_number': '1087'},
    'Satono Crown': {'alts': {1: 'Base', 2: 'Summer'}, 'uma_number': '1088'},
    'Cheval Grand': {'alts': {1: 'Base', 2: 'Summer'}, 'uma_number': '1089'},
    'Verxina': {'alts': {1: 'Base'}, 'uma_number': '1090'},
    'Vivlos': {'alts': {1: 'Base', 2: 'Summer'}, 'uma_number': '1091'},
    'Dantsu Flame': {'alts': {1: 'Base'}, 'uma_number': '1092'},
    'K.S. Miracle': {'alts': {1: 'Base', 2: 'Alt'}, 'uma_number': '1093'},
    'Jungle Pocket': {'alts': {1: 'Base'}, 'uma_number': '1094'},
    'Believe': {'alts': {1: 'Base'}, 'uma_number': '1095'},
    'No Reason': {'alts': {1: 'Base'}, 'uma_number': '1096'},
    'Still in Love': {'alts': {1: 'Base'}, 'uma_number': '1097'},
    'Copano Rickey': {'alts': {1: 'Base', 2: 'Parade'}, 'uma_number': '1098'},
    'Hokko Tarumae': {'alts': {1: 'Base', 2: 'Summer Trip'}, 'uma_number': '1099'},
    'Wonder Acute': {'alts': {1: 'Base', 2: 'Onsen'}, 'uma_number': '1100'}
}